# TAKE HOME LAB EXERCISE - 01

-----------

**(1). The value Range(0,10) ,  convert the list to `2D array`.**

In [2]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [7]:
random_arr = np.random.rand(5,2)
np.set_printoptions(precision=3)

random_arr

array([[0.059, 0.203],
       [0.749, 0.738],
       [0.068, 0.52 ],
       [0.391, 0.903],
       [0.945, 0.879]])

----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [10]:
x = np.arange(15)
np.set_printoptions(threshold =3)
x

array([ 0,  1,  2, ..., 12, 13, 14])

---------------------

**(4). An arrays of `x` and `y` , Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [15]:
x = np.arange(10).reshape(2,-1)
np.set_printoptions(threshold =1000)
y = np.repeat(1, 10).reshape(2,-1)

np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

----------------------

**(5). There are two array `x` and `y` ,output to be the matching items in both the array.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [16]:
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(x,y)

array([2, 4])

---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [49]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])


zz =np.hstack((x,y))
#print(zz)
#np.setdiff1d((zz,y))
xyz =np.setdiff1d(zz,y)
#p.setdiff1d(n34a,n34b)
print(xyz)

[1 2 3 4 5 5 6 7 8 9]
[1 2 3 4]


--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [23]:
X = np.arange(9).reshape(3,3)
print(X)
X[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [25]:
X = np.arange(9).reshape(3,3)
X[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [5]:
np.random.seed(10)
x = np.random.randint(20, size=10)
#print(x)
lst =[]
y = x.argsort()   
#print(y)
z = y.argsort()
print(z)

[4 2 6 0 8 7 9 3 5 1]


--------------------

**(10). Print a rank array of the same shape as a given numeric array `x`.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [17]:
np.random.seed(10)
x = np.random.randint(20, size=[2,5])
#print(x)

#print(x)

y = x.ravel().argsort();print(y)
z = y.argsort()
print(z.reshape(2,5))

[3 9 1 7 0 8 2 5 4 6]
[[4 2 6 0 8]
 [7 9 3 5 1]]


--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [59]:
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
y_1d = np.array([1,2,3])
xx =x_2d.T

zz =xx- y_1d
zz

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

----------------

# ----------------------------------HAPPY LEARNING--------------------------------------------------

-------------------