# IN CLASS LAB EXERCISES - 01

#### Import NumPy package as np

In [1]:
import numpy as np

####  01.  Create an empty array of 20 0's and replace the 4th object with the number 5

In [5]:
x =np.zeros(20)
x[3] =5
x

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

--------

#### 02. Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named array_copy

In [8]:
array_master =np.ones(20)
array_copy = array_master.copy()
print(array_copy)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


--------

#### 03.Create an array containing 30 1's and broadcast all the one's to the value 100

In [9]:
n1 =np.ones(30)
n2 = n1+99
n2

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

----------------------------------------------------

#### 04. Create an array of integers starting from 21 until 31 and name it as array1

####  ---     Create an array of integers starting from 11 until 21 and name it array2

####  ---    Calculate the difference between array1 and array2

In [10]:
array1 = np.arange(21,31)
array2 = np.arange(11,21)
diff = array1 -array2
diff

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

---------------------------------------------

#### 05. Create an array of all even integers from 2 to 10 and name it a1

#### --   Create an array of all even integers from 22 to 30 and name it a2

####    a) Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ]

In [25]:
a1 = np.arange(2,11,2);print(a1)
a2 = np.arange(22,31,2);print(a2)
stk = np.stack((a1,a2),axis =0)
#stack(a2)
print(stk)
stk.shape

[ 2  4  6  8 10]
[22 24 26 28 30]
[[ 2  4  6  8 10]
 [22 24 26 28 30]]


(2, 5)

-----------------------

####  b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]

In [27]:
stkcol = np.column_stack((a1,a2))
stkcol

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

--------------

#### 06. Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column

In [30]:
mat = np.arange(5*6).reshape(5,6)
print(mat)
x = mat[1,2]
x

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


8

--------------------

#### 07. Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [37]:
k =np.identity(10)
b = np.where(k==0,21,k)
b

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

In [81]:
k =np.identity(10)
k[k==0] = 21
k

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

--------------------

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

#### 08. Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [42]:
ran =np.random.rand(10,1)
print(ran)
j = ran>0.2
j

[[0.77579363]
 [0.65216233]
 [0.34297805]
 [0.92963853]
 [0.77959629]
 [0.2127217 ]
 [0.08700758]
 [0.16578081]
 [0.47171743]
 [0.66489894]]


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True]])

-------------------

#### 09. Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [43]:
stdra =np.random.randn(5,2)
stdra

array([[ 0.2581788 ,  0.26097608],
       [ 0.45667867, -0.2504333 ],
       [ 0.35770965, -0.40321427],
       [ 0.15336081,  0.00392236],
       [ 0.39064336, -0.79128653]])

-----------------------------

#### 10. Create an array of 30 linearly spaced points between 0 and 100:

In [53]:
x = np.linspace(0,100,30)
print(x.shape)
x

(30,)


array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

---------------------------

## Numpy Indexing and Selections

#### 11. Using the below given Matrix, generate the output for the below questions.

In [61]:
xx =np.arange(10*10).reshape(10,10)
xx

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

----------------

#### a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [62]:
y = xx[8:,:3]
y

array([[80, 81, 82],
       [90, 91, 92]])

------

#### b) Retrieve the value 55 from the above matrix using index & selection technique

In [63]:
z =xx[5,5]
z

55

--------------

#### c) Retrieve the values from the 3rd column in the above matrix

In [76]:
xx[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

---------------

#### d) Retrieve the values from the 4th row in the above matrix

In [75]:
xx[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

-----------------

#### e) Retrieve values from the 2nd & 4th rows in the above matrix

In [77]:
xx[[1,3]]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

--------------

### Calculate the following values for the given matrix

#### a) Calculate sum of all the values in the matrix

In [68]:
np.sum(xx)

4950

--------------

#### b) Calculate standard deviation of all the values in the matrix

In [72]:
np.std(xx)

28.86607004772212

------

#### c) Calculate the variance of all values in the matrix

In [73]:
np.var(xx)

833.25

-----------

#### d) Calculate the mean of all values in the matrix

In [74]:
np.mean(xx)

49.5

-------------

#### e) Retrieve the largest number from the matrix

In [78]:
np.amax(xx)

99

--------------

#### f) Retrieve the smallest number from the matrix

In [79]:
np.amin(xx)

0

-------

# -------------------------------- HAPPY LEARNING -------------------------------

--------------------------------