In [3]:
import numpy as np 

In [4]:
list1 =(1,2,3,4,5)  # tuple
str1 = ['srl','ram',1]
print(type(list1))

Ar =np.array(list1)  # object can be any single variable,If it is 2 values we need to pass as seq.
ar2 = np.array((1,2))
Ar1 =np.array(str1)# it takes string ad converts as nd aray

print(type(Ar))
print(type(Ar1))
print(type(ar2))

print(Ar1)
print(Ar)
print(ar2)

#array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

#Create an array.

<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
['srl' 'ram' '1']
[1 2 3 4 5]
[1 2]


In [5]:
Ar =np.array(list1,dtype=float,copy =False) # we can change he data type by dtype

In [6]:
Ar

array([1., 2., 3., 4., 5.])

In [9]:
#Ar.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [11]:
np.indices(Ar)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [15]:
x = np.arange(20).reshape(5, 4)
print(x)
row, col = np.indices((2, 3))
print(row)
print(col)

x[row, col]
#array([[0, 1, 2],
   #    [4, 5, 6]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[0 0 0]
 [1 1 1]]
[[0 1 2]
 [0 1 2]]


array([[0, 1, 2],
       [4, 5, 6]])

In [5]:
lst2 = [1,2,3.0]

upcast = np.array(lst2)#upcasting
multi  = np.array([[1,2,3],[1,2,4]])#multi array
ndim  = np.array([1,2,3],ndmin=4)#ndimensions
complex1 = np.array([1, 2, 3], dtype=complex) #

print(upcast)
print(multi)
print(ndim)
print(complex1)

#upcasting 

[1. 2. 3.]
[[1 2 3]
 [1 2 4]]
[[[[1 2 3]]]]
[1.+0.j 2.+0.j 3.+0.j]


In [6]:
type(np.array(np.mat('1 2; 3 4')))

numpy.ndarray

In [7]:
type(np.mat('1 2; 3 4'))

numpy.matrixlib.defmatrix.matrix

In [8]:
multi.shape # rows,col

(2, 3)

In [9]:
multi.size # no of elements

6

In [10]:
len(multi)

2

In [11]:
row = [[1],[2],[3],[4],[5]]
print(row)

[[1], [2], [3], [4], [5]]


In [12]:
len(row)

5

In [13]:
multi.itemsize #size of each byte in my windows machine

4

In [14]:
total_memory_occupied = multi.size * multi.itemsize
total_memory_occupied

24

# arange

In [15]:
#arange(...)
#    arange([start,] stop[, step,], dtype=None)

In [16]:
print(np.arange(50))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [17]:
res =np.arange(1,100,2)
print(np.arange(1,100,2).shape)

(50,)


In [18]:
print(np.arange(1,100,2,dtype = complex)) # we can specify dtatype in arange

[ 1.+0.j  3.+0.j  5.+0.j  7.+0.j  9.+0.j 11.+0.j 13.+0.j 15.+0.j 17.+0.j
 19.+0.j 21.+0.j 23.+0.j 25.+0.j 27.+0.j 29.+0.j 31.+0.j 33.+0.j 35.+0.j
 37.+0.j 39.+0.j 41.+0.j 43.+0.j 45.+0.j 47.+0.j 49.+0.j 51.+0.j 53.+0.j
 55.+0.j 57.+0.j 59.+0.j 61.+0.j 63.+0.j 65.+0.j 67.+0.j 69.+0.j 71.+0.j
 73.+0.j 75.+0.j 77.+0.j 79.+0.j 81.+0.j 83.+0.j 85.+0.j 87.+0.j 89.+0.j
 91.+0.j 93.+0.j 95.+0.j 97.+0.j 99.+0.j]


In [19]:
np.arange(1,100,2,dtype = complex).shape

(50,)

## Reshape

In [20]:
print(np.arange(1,100,2).reshape(25,2))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]
 [25 27]
 [29 31]
 [33 35]
 [37 39]
 [41 43]
 [45 47]
 [49 51]
 [53 55]
 [57 59]
 [61 63]
 [65 67]
 [69 71]
 [73 75]
 [77 79]
 [81 83]
 [85 87]
 [89 91]
 [93 95]
 [97 99]]


In [21]:
res
np.reshape(res,(25,2)) # ndarray.reshape : Equivalent method.



array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23],
       [25, 27],
       [29, 31],
       [33, 35],
       [37, 39],
       [41, 43],
       [45, 47],
       [49, 51],
       [53, 55],
       [57, 59],
       [61, 63],
       [65, 67],
       [69, 71],
       [73, 75],
       [77, 79],
       [81, 83],
       [85, 87],
       [89, 91],
       [93, 95],
       [97, 99]])

# broad casting

In [22]:
n68 =np.arange(1,49).reshape(6,8)
n18 =  np.arange(50, 50+8).reshape(1,8)# need to have same shape or one with 1 row/col and other with same as row/col of first one.
n18 +n68

array([[ 51,  53,  55,  57,  59,  61,  63,  65],
       [ 59,  61,  63,  65,  67,  69,  71,  73],
       [ 67,  69,  71,  73,  75,  77,  79,  81],
       [ 75,  77,  79,  81,  83,  85,  87,  89],
       [ 83,  85,  87,  89,  91,  93,  95,  97],
       [ 91,  93,  95,  97,  99, 101, 103, 105]])

In [23]:
'''
n68 =np.arange(1,49).reshape(6,8)
n48 =  np.arange(50, 50+(6*16)).reshape(6,16)
n48 +n68'''


'\nn68 =np.arange(1,49).reshape(6,8)\nn48 =  np.arange(50, 50+(6*16)).reshape(6,16)\nn48 +n68'

In [24]:
n18 - n68

array([[49, 49, 49, 49, 49, 49, 49, 49],
       [41, 41, 41, 41, 41, 41, 41, 41],
       [33, 33, 33, 33, 33, 33, 33, 33],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [17, 17, 17, 17, 17, 17, 17, 17],
       [ 9,  9,  9,  9,  9,  9,  9,  9]])

In [25]:
n18 %n68

array([[ 0,  1,  1,  1,  4,  1,  0,  1],
       [ 5,  1,  8,  5,  2, 13, 11,  9],
       [16, 15, 14, 13, 12, 11, 10,  9],
       [ 0, 25, 25, 25, 25, 25, 25, 25],
       [17, 17, 17, 17, 17, 17, 17, 17],
       [ 9,  9,  9,  9,  9,  9,  9,  9]], dtype=int32)

In [26]:
n68 =n18 *n68
n68.shape

(6, 8)

# Transpose

In [27]:
n68.T.shape

(8, 6)

In [28]:
n23 = np.arange(2*3).reshape(2,3)

In [29]:
n34 = np.arange(10 ,10+3*4).reshape(3,4)

## Dot product

In [30]:
n24 = n23.dot(n34+10)   # n23 34  ## first arr col == second arr row
n24

array([[ 80,  83,  86,  89],
       [296, 308, 320, 332]])

# element selection using indexing & slicing

In [31]:
n24[1,3] # slicing[row,col] 

332

In [32]:
n24[[0,1],2] #if we want 2 rows or 2 cols then we need to give as seq

array([ 86, 320])

In [33]:
n24[(0,1),2] # we can also use tuple as seq

array([ 86, 320])

In [34]:
n681 = np.arange(550,550+6*8).reshape(6,8)
n681

array([[550, 551, 552, 553, 554, 555, 556, 557],
       [558, 559, 560, 561, 562, 563, 564, 565],
       [566, 567, 568, 569, 570, 571, 572, 573],
       [574, 575, 576, 577, 578, 579, 580, 581],
       [582, 583, 584, 585, 586, 587, 588, 589],
       [590, 591, 592, 593, 594, 595, 596, 597]])

In [35]:
n681[1][2]

560

In [36]:
n681[[1],[2]] #with comma  and seq as zpping

array([560])

In [37]:
n681[[0,1],(1,2)] #slicing using  vectors as list & tuple

array([551, 560])

## Zipping

In [38]:
mylist1 = [1,2,3,4,5]
mylist2 = [4,5,6,7,8,9]
zipp =list(zip(mylist1,mylist2))  # zipping elment wise combining as a tuple.
zipp

[(1, 4), (2, 5), (3, 6), (4, 7), (5, 8)]

In [39]:
n681[[0,1,3],(1,2,4)] # zipping will happen when we do vector slicing

array([551, 560, 578])

In [40]:
n681[:,:]

array([[550, 551, 552, 553, 554, 555, 556, 557],
       [558, 559, 560, 561, 562, 563, 564, 565],
       [566, 567, 568, 569, 570, 571, 572, 573],
       [574, 575, 576, 577, 578, 579, 580, 581],
       [582, 583, 584, 585, 586, 587, 588, 589],
       [590, 591, 592, 593, 594, 595, 596, 597]])

In [41]:
n681[:,[2,3,4]]

array([[552, 553, 554],
       [560, 561, 562],
       [568, 569, 570],
       [576, 577, 578],
       [584, 585, 586],
       [592, 593, 594]])

In [42]:
n681[:,2:3]

array([[552],
       [560],
       [568],
       [576],
       [584],
       [592]])

# Broad casting again

In [43]:
n64 = np.arange(24).reshape(6,4)
n64

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
n64 +10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [45]:
n61 = np.arange(6).reshape(6,1)
n61

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [46]:
nbrod = n61 + n64  # n61 is getting added to all of the col

nbrod

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23],
       [25, 26, 27, 28]])

# 3D

In [47]:
n234 = np.arange(24).reshape(2,3,4)
n234.shape
print(n234)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [48]:
n231 = np.arange(6).reshape(2,3,1)
n231.shape
print(n231)

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]


In [49]:
n234a = n234 + n231  # 23 4 ,23 1   # two dimen needs to be same an other needs to be 1 in atleast one array
n234a

array([[[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]],

       [[15, 16, 17, 18],
        [20, 21, 22, 23],
        [25, 26, 27, 28]]])

# slicing in 3D

In [50]:
n234a[0] # first row

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [51]:
n234a[0,0] # 1st row,1col

array([0, 1, 2, 3])

In [52]:
n234a[0,0,0] # 1st row,1col,1 depth

0

In [53]:
n234a[1:3,1:3,1:5]

array([[[21, 22, 23],
        [26, 27, 28]]])

In [54]:
n234a

array([[[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]],

       [[15, 16, 17, 18],
        [20, 21, 22, 23],
        [25, 26, 27, 28]]])

In [55]:
n234a[[0,1],[0,1],[0,1]]

array([ 0, 21])

In [56]:
n234a[:,[1,2],[1,2]]

array([[ 6, 12],
       [21, 27]])

In [57]:
n234a[[0,1],:,[1,2]]  # zipping works when we have vectors and other will keep o adding to that zipped vallues 



array([[ 1,  6, 11],
       [17, 22, 27]])

# Randomisation

### randint

In [58]:
np.random.randint(1,100,size =10)
#randint(low, high=None, size=None, dtype='l') low : int,high : int, optional,size : int or tuple of ints, optional


array([64, 93, 58, 80, 70, 78, 13, 87, 87, 22])

In [59]:
np.random.randint(1,100,size =[4,2])


array([[32, 45],
       [42, 40],
       [77, 61],
       [87, 41]])

In [60]:
np.random.randint(20,size =[4,2])


array([[ 4,  1],
       [16,  9],
       [18,  5],
       [ 5, 12]])

In [69]:
np.random.rand(4,2)
# rand(d0, d1, ..., dn)
#'''
#Random values in a given shape.

#Create an array of the given shape and populate it with
#random samples from a uniform distribution
#over ``[0, 1)``.
#'''

array([[0.83273105, 0.94695467],
       [0.67918819, 0.26926732],
       [0.71943893, 0.70789761],
       [0.75663761, 0.22227509]])

In [70]:
np.random.randn(2,4)

array([[ 0.78653957,  0.43351899, -0.69877809, -0.27201042],
       [ 0.60158622,  0.12063849,  0.62782737, -0.67025996]])

## zeros

In [71]:
n =np.zeros(3)
n


array([0., 0., 0.])

In [72]:
'''
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
    '''

"\nzeros(shape, dtype=float, order='C')\n\nReturn a new array of given shape and type, filled with zeros.\n\nParameters\n----------\nshape : int or tuple of ints\n    Shape of the new array, e.g., ``(2, 3)`` or ``2``.\ndtype : data-type, optional\n    The desired data-type for the array, e.g., `numpy.int8`.  Default is\n    `numpy.float64`.\n    "

In [73]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.zeros([3,4],dtype = np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [75]:
np.ones(3)

array([1., 1., 1.])

In [76]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
x =np.ones((3,4),dtype =int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [78]:
np.zeros_like(x)#Array of zeros with the same shape and type as `a`.

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [79]:
np.full((3,4),fill_value = 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [80]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
np.identity(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [82]:
np.empty_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [83]:
np.eye(5,k =1) # whenk =0 eye = identity

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [84]:
n68 = np.random.randint(2,60,size =(6,8)); print(n68)

[[19 51 22 40 20  3 18 41]
 [15 42 45 10 46 40 47 16]
 [22 14  2 25  8 53  2 31]
 [ 3 42 18 53 52 45  7 20]
 [45 47  4  2 37 50 22 32]
 [51  4 23 59 58  2 20 41]]


In [85]:
np.unique(n68)

array([ 2,  3,  4,  7,  8, 10, 14, 15, 16, 18, 19, 20, 22, 23, 25, 31, 32,
       37, 40, 41, 42, 45, 46, 47, 50, 51, 52, 53, 58, 59])

In [86]:
np.unique(n68,return_index=True,return_inverse=True)

(array([ 2,  3,  4,  7,  8, 10, 14, 15, 16, 18, 19, 20, 22, 23, 25, 31, 32,
        37, 40, 41, 42, 45, 46, 47, 50, 51, 52, 53, 58, 59]),
 array([18,  5, 34, 30, 20, 11, 17,  8, 15,  6,  0,  4,  2, 42, 19, 23, 39,
        36,  3,  7,  9, 10, 12, 14, 37,  1, 28, 21, 44, 43], dtype=int64),
 array([10, 25, 12, 18, 11,  1,  9, 19,  7, 20, 21,  5, 22, 18, 23,  8, 12,
         6,  0, 14,  4, 27,  0, 15,  1, 20,  9, 27, 26, 21,  3, 11, 21, 23,
         2,  0, 17, 24, 12, 16, 25,  2, 13, 29, 28,  0, 11, 19],
       dtype=int64))

In [87]:
#np.unique(['ar', 'return_index=False', 'return_inverse=False', 'return_counts=False', 'axis=None'],)

In [88]:
i,unique_counts = np.unique(n68,return_counts=True)
unique_counts

array([4, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 3, 3, 1, 1, 1, 1, 1, 2, 2, 2, 3,
       1, 2, 1, 2, 1, 2, 1, 1], dtype=int64)

In [89]:
'''
Signature: np.ravel(a, order='C')
Docstring:
Return a contiguous flattened array.
'''

"\nSignature: np.ravel(a, order='C')\nDocstring:\nReturn a contiguous flattened array.\n"

In [90]:
n68.size

48

In [91]:
np.ravel(n68)

array([19, 51, 22, 40, 20,  3, 18, 41, 15, 42, 45, 10, 46, 40, 47, 16, 22,
       14,  2, 25,  8, 53,  2, 31,  3, 42, 18, 53, 52, 45,  7, 20, 45, 47,
        4,  2, 37, 50, 22, 32, 51,  4, 23, 59, 58,  2, 20, 41])

In [92]:
n68.size

48

In [93]:
n68

array([[19, 51, 22, 40, 20,  3, 18, 41],
       [15, 42, 45, 10, 46, 40, 47, 16],
       [22, 14,  2, 25,  8, 53,  2, 31],
       [ 3, 42, 18, 53, 52, 45,  7, 20],
       [45, 47,  4,  2, 37, 50, 22, 32],
       [51,  4, 23, 59, 58,  2, 20, 41]])

# intersectId, setdiff Id

In [94]:
n34a = np.random.randint(2,20,size =(3,4));print(n34a)
n34b = np.random.randint(10,25,size =(3,4));print(n34b)

[[11 18 10  9]
 [ 5 12  3  6]
 [19  7  9  5]]
[[17 14 24 17]
 [19 16 13 22]
 [22 17 14 18]]


In [95]:
#np.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
np.intersect1d(n34a,n34b) # it takes only common values of both

array([18, 19])

In [96]:
np.intersect1d(n34a,n34b,assume_unique=True)#assume_unique : bool
#    If True, the input arrays are both assumed to be unique, which
#    can speed up the calculation.  Default is False.

array([ 5,  9, 14, 17, 17, 18, 19, 22])

In [97]:
from functools import reduce
reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
# to do intersect for more than 2 need to use reduce

array([3])

## Setdiff1D

In [98]:
nsd = np.setdiff1d(n34a,n34b) # A-B in venn diagram
nsd
#>>> a = np.array([1, 2, 3, 2, 4, 1])
#>>> b = np.array([3, 4, 5, 6])
#>>> np.setdiff1d(a, b)
#array([1, 2])

array([ 3,  5,  6,  7,  9, 10, 11, 12])

In [99]:
np.union1d(n34a,n34b)

array([ 3,  5,  6,  7,  9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 22, 24])

In [100]:
n68

array([[19, 51, 22, 40, 20,  3, 18, 41],
       [15, 42, 45, 10, 46, 40, 47, 16],
       [22, 14,  2, 25,  8, 53,  2, 31],
       [ 3, 42, 18, 53, 52, 45,  7, 20],
       [45, 47,  4,  2, 37, 50, 22, 32],
       [51,  4, 23, 59, 58,  2, 20, 41]])

In [101]:
n68.max()

59

In [102]:
np.amax(n68)

59

In [103]:
print(np.amax(n68,axis = 0))# horizontal
print(np.amax(n68,axis = 1))# horizontal

[51 51 45 59 58 53 47 41]
[51 47 53 53 50 59]


In [104]:
n68.min()

2

In [105]:
n68.argmin()# returns the index of the minimum value

18

In [106]:
print(np.amin(n68))
print(np.amin(n68,axis =0))#taking min of each col
print(np.amin(n68,axis =1))# taking min of each row


2
[ 3  4  2  2  8  2  2 16]
[ 3 10  2  3  2  2]


In [107]:
np.sum(n68) # np.sum( ['a', 'axis=None', 'dtype=None', 'out=None', 'keepdims=<no value>', 'initial=<no value>'],)

1369

In [108]:
np.sum(n68,axis=0)

array([155, 200, 114, 189, 221, 193, 116, 181])

In [109]:
n68.sum()

1369

In [110]:
np.mean(n68)#n68.mean()

28.520833333333332

In [111]:
np.median(n68)#n68.median()

24.0

In [112]:
np.std(n68)#n68.std()

18.055458065976122

In [113]:
np.var(n68)

325.99956597222223

In [114]:
np.sort(n68.ravel())

array([ 2,  2,  2,  2,  3,  3,  4,  4,  7,  8, 10, 14, 15, 16, 18, 18, 19,
       20, 20, 20, 22, 22, 22, 23, 25, 31, 32, 37, 40, 40, 41, 41, 42, 42,
       45, 45, 45, 46, 47, 47, 50, 51, 51, 52, 53, 53, 58, 59])

In [115]:
n68

array([[19, 51, 22, 40, 20,  3, 18, 41],
       [15, 42, 45, 10, 46, 40, 47, 16],
       [22, 14,  2, 25,  8, 53,  2, 31],
       [ 3, 42, 18, 53, 52, 45,  7, 20],
       [45, 47,  4,  2, 37, 50, 22, 32],
       [51,  4, 23, 59, 58,  2, 20, 41]])

In [116]:
np.sort(n68)

array([[ 3, 18, 19, 20, 22, 40, 41, 51],
       [10, 15, 16, 40, 42, 45, 46, 47],
       [ 2,  2,  8, 14, 22, 25, 31, 53],
       [ 3,  7, 18, 20, 42, 45, 52, 53],
       [ 2,  4, 22, 32, 37, 45, 47, 50],
       [ 2,  4, 20, 23, 41, 51, 58, 59]])

## condition access

In [117]:
n68.flatten()#  numpy.ravel : equivalent function

array([19, 51, 22, 40, 20,  3, 18, 41, 15, 42, 45, 10, 46, 40, 47, 16, 22,
       14,  2, 25,  8, 53,  2, 31,  3, 42, 18, 53, 52, 45,  7, 20, 45, 47,
        4,  2, 37, 50, 22, 32, 51,  4, 23, 59, 58,  2, 20, 41])

In [118]:
n68.ravel()

array([19, 51, 22, 40, 20,  3, 18, 41, 15, 42, 45, 10, 46, 40, 47, 16, 22,
       14,  2, 25,  8, 53,  2, 31,  3, 42, 18, 53, 52, 45,  7, 20, 45, 47,
        4,  2, 37, 50, 22, 32, 51,  4, 23, 59, 58,  2, 20, 41])

In [119]:
mask = n68>10
mask

array([[ True,  True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True, False,  True],
       [False,  True,  True,  True,  True,  True, False,  True],
       [ True,  True, False, False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True, False,  True,  True]])

In [120]:
n68[mask]#we get only values that are true after flattening

array([19, 51, 22, 40, 20, 18, 41, 15, 42, 45, 46, 40, 47, 16, 22, 14, 25,
       53, 31, 42, 18, 53, 52, 45, 20, 45, 47, 37, 50, 22, 32, 51, 23, 59,
       58, 20, 41])

In [121]:
np.sum(n68>45)# it takes sum of all numbers whos alues are true

11

In [122]:
np.any(n68>10)

True

In [123]:
np.all(n68>10)

False

## hstack

In [124]:
n34a = np.random.randint(20,size =(3,4));print(n34a)
n34b = np.random.randint(20,size =(3,4));print(n34b)
n34c = np.random.randint(20,size =(3,6));print(n34c)
np.hstack((n34a,n34b,n34c))
# we can have any no of cols but rows need to be same** horizontal stacking

[[ 6 14  2 16]
 [ 0 17  1 19]
 [11  0  5  3]]
[[ 4  3 13  0]
 [14 12  6 18]
 [10  9 13  5]]
[[14  0  9  5  2 10]
 [ 9  5 11  1 17  8]
 [ 1 15  1 13 17  4]]


array([[ 6, 14,  2, 16,  4,  3, 13,  0, 14,  0,  9,  5,  2, 10],
       [ 0, 17,  1, 19, 14, 12,  6, 18,  9,  5, 11,  1, 17,  8],
       [11,  0,  5,  3, 10,  9, 13,  5,  1, 15,  1, 13, 17,  4]])

In [19]:
n35a = np.random.randint(20,size =(4,5));print(n35a)
n35b = np.random.randint(20,size =(6,5));print(n35a)
n35c = np.random.randint(20,size =(8,5));print(n35a)
print(n35a.shape)
print(n35b.shape)
print(n35c.shape)
# # we can have any no of rows but rows need to be same** vertical stacking

n35v = np.vstack((n35a,n35b,n35c))
print(n35v.shape)

n35v

[[15 12  2  2 17]
 [18  0 19 11  7]
 [11 19  2 10  8]
 [12  5 14  3  5]]
[[15 12  2  2 17]
 [18  0 19 11  7]
 [11 19  2 10  8]
 [12  5 14  3  5]]
[[15 12  2  2 17]
 [18  0 19 11  7]
 [11 19  2 10  8]
 [12  5 14  3  5]]
(4, 5)
(6, 5)
(8, 5)
(18, 5)


array([[15, 12,  2,  2, 17],
       [18,  0, 19, 11,  7],
       [11, 19,  2, 10,  8],
       [12,  5, 14,  3,  5],
       [ 2, 11,  1, 16, 17],
       [ 8, 10, 18,  0,  9],
       [ 4,  9, 14, 16, 13],
       [ 8,  8,  2, 14,  7],
       [ 9,  6,  6, 14,  4],
       [18,  0,  0, 10, 15],
       [12,  6,  4, 15, 12],
       [14, 12,  2, 19, 16],
       [17,  1,  8, 17, 11],
       [ 5,  9,  5,  3,  0],
       [15, 10,  3,  4, 11],
       [ 9, 13,  4, 11,  3],
       [ 4, 19, 19,  7, 18],
       [ 3, 18,  5,  7,  5]])

In [127]:
np.stack((n34a,n34b,n34c))

ValueError: all input arrays must have the same shape

In [ ]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
#print(arrays.shape)
np.stack(arrays, axis=0).shape

In [ ]:
n36a = np.random.randint(20,size =(4,5,2));print(n36a)
n36b = np.random.randint(20,size =(4,5,5));print(n36b)
n36c = np.random.randint(20,size =(4,5,10));print(n36c)
print(n36a.shape)
print(n36b.shape)
print(n36c.shape)

n35d = np.dstack((n36a,n36b,n36c))
print(n35d.shape)

n35d

In [ ]:
print(n34a)
print(n34b)
np.column_stack((n34a,n34b))

In [128]:
print(n68)
k = np.hsplit(n68,4)
print(k)

[[19 51 22 40 20  3 18 41]
 [15 42 45 10 46 40 47 16]
 [22 14  2 25  8 53  2 31]
 [ 3 42 18 53 52 45  7 20]
 [45 47  4  2 37 50 22 32]
 [51  4 23 59 58  2 20 41]]
[array([[19, 51],
       [15, 42],
       [22, 14],
       [ 3, 42],
       [45, 47],
       [51,  4]]), array([[22, 40],
       [45, 10],
       [ 2, 25],
       [18, 53],
       [ 4,  2],
       [23, 59]]), array([[20,  3],
       [46, 40],
       [ 8, 53],
       [52, 45],
       [37, 50],
       [58,  2]]), array([[18, 41],
       [47, 16],
       [ 2, 31],
       [ 7, 20],
       [22, 32],
       [20, 41]])]


In [129]:
x = np.hsplit(n68,[1,4,6])
print(x)

[array([[19],
       [15],
       [22],
       [ 3],
       [45],
       [51]]), array([[51, 22, 40],
       [42, 45, 10],
       [14,  2, 25],
       [42, 18, 53],
       [47,  4,  2],
       [ 4, 23, 59]]), array([[20,  3],
       [46, 40],
       [ 8, 53],
       [52, 45],
       [37, 50],
       [58,  2]]), array([[18, 41],
       [47, 16],
       [ 2, 31],
       [ 7, 20],
       [22, 32],
       [20, 41]])]


In [130]:
print(n68)
x = np.vsplit(n68,[1,4,6]);print(x)

[[19 51 22 40 20  3 18 41]
 [15 42 45 10 46 40 47 16]
 [22 14  2 25  8 53  2 31]
 [ 3 42 18 53 52 45  7 20]
 [45 47  4  2 37 50 22 32]
 [51  4 23 59 58  2 20 41]]
[array([[19, 51, 22, 40, 20,  3, 18, 41]]), array([[15, 42, 45, 10, 46, 40, 47, 16],
       [22, 14,  2, 25,  8, 53,  2, 31],
       [ 3, 42, 18, 53, 52, 45,  7, 20]]), array([[45, 47,  4,  2, 37, 50, 22, 32],
       [51,  4, 23, 59, 58,  2, 20, 41]]), array([], shape=(0, 8), dtype=int32)]


In [131]:
n26  = np.arange(2*5*8).reshape(2,5,8);print(n26)


[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47]
  [48 49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62 63]
  [64 65 66 67 68 69 70 71]
  [72 73 74 75 76 77 78 79]]]


In [132]:
x = np.dsplit(n26,[1,4,6]);print(x)

[array([[[ 0],
        [ 8],
        [16],
        [24],
        [32]],

       [[40],
        [48],
        [56],
        [64],
        [72]]]), array([[[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27],
        [33, 34, 35]],

       [[41, 42, 43],
        [49, 50, 51],
        [57, 58, 59],
        [65, 66, 67],
        [73, 74, 75]]]), array([[[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29],
        [36, 37]],

       [[44, 45],
        [52, 53],
        [60, 61],
        [68, 69],
        [76, 77]]]), array([[[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31],
        [38, 39]],

       [[46, 47],
        [54, 55],
        [62, 63],
        [70, 71],
        [78, 79]]])]


In [133]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [134]:
np.linspace(1,20,5)#np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

## Rank in numpy()

In [135]:
np.random.seed(10)
x = np.random.randint(20, size=10)
print(x)
#lst =[]
y = x.argsort()   
print(y)
z = y.argsort()
print(z)

[ 9  4 15  0 17 16 17  8  9  0]
[3 9 1 7 0 8 2 5 4 6]
[4 2 6 0 8 7 9 3 5 1]


In [1]:
import numpy as np
lst =[1,2,3,'srk']
a = np.array(lst)
type(a)
print(a)# it converts all to strings# homogenous 'numpy is homogenous'
a+1 #we get error as it cant handle addition with strings

['1' '2' '3' 'srk']


TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [2]:
import numpy as np
lst =[1,2,3]
a = np.array(lst)
type(a)
print(a)
a+1 

[1 2 3]


array([2, 3, 4])

In [17]:
n35a.

NameError: name 'n234a' is not defined